Srodunia_Challenges/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('srodunia.urls')),
    path('', include('scraper.urls'))
]

scraper/urls.py
from django.urls import path

from scraper.views import ScrapeClubMembers, ScrapeStarredSegments, ScrapeHomeView, ScrapeSegmentsLeaderboards

urlpatterns = [
    path('scrape/', ScrapeHomeView.as_view(), name='scrape_home'),
    path('scrape/leaderboards/', ScrapeSegmentsLeaderboards.as_view(), name='scrape_leaderboards'),
    path('scrape/members/', ScrapeClubMembers.as_view(), name='scrape_members'),
    path('scrape/segments/', ScrapeStarredSegments.as_view(), name='scrape_segments'),
]

scraper/models.py
from django.db import models

SEGMENT_TYPES = (
    ('1', '1 - 4 minuty'),
    ('5', '5 - 15 minut'),
    ('20', '16 - 44 minut'),
    ('60', '45 - 110 minut'),
    ('110', 'powyżej 110 minut'),
)
SEGMENT_CATEGORIES = (
    ('-1', 'DH: < 0%'),
    ('0', 'FLAT: 0 - 4%'),
    ('1', 'ROLL: 4 - 8%'),
    ('2', 'HILL: 8 - 12%'),
    ('3', 'CLIMB: > 12%'),
)
SEGMENT_ZONES = (
    ('5', 'MAX 5 Pkt'),
    ('6', 'MAX 6 Pkt'),
    ('7', 'MAX 7 Pkt'),
)
SEGMENT_SECTIONS = (
    ('NW', '↖️ PN-ZACH'),
    ('NE', 'PN-WSCH ↗️'),
    ('SW', '↙️ PD-ZACH'),
    ('SE', 'PD-WSCH ↘️'),
)


class SegmentDescription(models.Model):
    strava_segment_id = models.IntegerField(unique=True)
    strava_segment_name = models.CharField(max_length=255)
    distance = models.FloatField(null=True)
    average_grade = models.FloatField(null=True) #TODO: bardziej wiarygodne dane odnośnie max gradient znajdują się na veloviewer
    maximum_grade = models.FloatField(null=True) #TODO: własne miara czy segment jest płaski, pofałdowany, górka, czy sztfajfa (elev.gain / dystnas)
    start_latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    start_longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    end_latitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    end_longitude = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    climb_category = models.IntegerField(null=True)
    total_elevation_gain = models.FloatField(null=True)
    strava_effort_count = models.IntegerField(null=True)
    star_count = models.IntegerField(null=True)
    srodunia_segment_type = models.CharField(choices=SEGMENT_TYPES, null=True, max_length=255)
    srodunia_segment_cat = models.CharField(choices=SEGMENT_CATEGORIES, null=True, max_length=255)
    srodunia_segment_zone = models.CharField(choices=SEGMENT_ZONES, null=True, max_length=255)
    srodunia_segment_section = models.CharField(choices=SEGMENT_SECTIONS, null=True, max_length=255)
    date_added = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.strava_segment_name}'


class StravaClubs(models.Model):
    club_id = models.IntegerField(unique=True)
    club_name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.club_name}'


class AthleteDetails(models.Model):
    strava_athlete_id = models.IntegerField(unique=True)
    strava_athlete_name = models.CharField(max_length=255)
    srodunia_athlete_name = models.CharField(max_length=255, null=True)
    athlete_avatar_img_url = models.URLField()
    role = models.CharField(max_length=32)
    club_id = models.ManyToManyField(StravaClubs)
    date_added = models.DateField(auto_now_add=True, null=True)

    def __str__(self):
        return f'{self.strava_athlete_name}'


class StravaSegmentLeaderboard(models.Model):
    leaderboard_unique_week_number = models.CharField(max_length=255, null=True)
    rank = models.IntegerField() #TODO: jest możliwość zeskrobania KOMa dla segmentu
    strava_athlete_id = models.ForeignKey(AthleteDetails, on_delete=models.CASCADE, null=True)
    strava_activity_id = models.CharField(max_length=255)
    strava_effort_id = models.CharField(max_length=255)
    strava_segement_id = models.ForeignKey(SegmentDescription, on_delete=models.CASCADE, null=True)
    effort_date = models.DateField()
    avg_speed = models.CharField(max_length=32)
    avg_hr = models.CharField(max_length=32, null=True)
    avg_power = models.CharField(max_length=32, null=True)
    vam = models.CharField(max_length=32, null=True)
    time_result = models.CharField(max_length=10)
    time_filter = models.CharField(max_length=32, null=True)
    club_id = models.ForeignKey(StravaClubs, on_delete=models.CASCADE, null=True)
    date_added = models.DateField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True, null=True)
    points = models.IntegerField(null=True)
    week_number = models.IntegerField(null=True)

scraper/views.py
from django.shortcuts import render
from django.views import View

from scraper.scrape_club_members import get_my_club_members
from scraper.scrape_starred_segments import push_segment_to_db
from scraper.scrape_leaderboards import scrape_weekly_leaderboards
from scraper.models import AthleteDetails, SegmentDescription, StravaSegmentLeaderboard

from scraper.strava_scraper import StravaScraper
from bs4 import BeautifulSoup


class ScrapeHomeView(View):
    def get(self, request):
        return render(request, 'scraper/scraper_home.html', context={})

    def post(self, request):
        ...


class ScrapeClubMembers(View):
    def get(self, request):
        athletes = AthleteDetails.objects.all()
        return render(request, 'scraper/scrape_members.html', context={'athletes': athletes})

    def post(self, request):
        get_my_club_members('mirko.dravik@gmail.com', 'Dravikson123',
                            '515628')  # TODO: zrobić do tego widok, żeby wysyłać postem dane co ma zeskrpować ze stravy (lista segmentów, członków klubu, leaderboardy)
        return self.get(request)


class ScrapeSegmentsLeaderboards(View):
    def get(self, request):
        segments_to_scrape = SegmentDescription.objects.all()
        return render(request, 'scraper/scrape_leaderboards.html', context={'segments': segments_to_scrape})

    def post(self, request):
        segments_to_scrape = request.POST.getlist('strava_segment_id')
        time_frame = request.POST.get('time_frame')
        print(segments_to_scrape)
        print(time_frame)
        scrape_weekly_leaderboards('mirko.dravik@gmail.com', 'Dravikson123', segments_to_scrape, time_frame)
        return self.get(request)


class ScrapeStarredSegments(View):
    def get(self, request):
        segments = SegmentDescription.objects.all()
        return render(request, 'scraper/scrape_segments.html', context={'segments': segments})

    def post(self, request):
        push_segment_to_db()
        return self.get(request)

scraper/templates/scraper/scrape_leaderboards.html
{% extends 'base.html' %}
{% block title %}
    Scrape Leaderboards
{% endblock %}
{% block content %}
    <form role="form" method="post">{% csrf_token %}
        <button class="btn btn-outline-danger bg-white bg-danger position-fixed" type="submit">UAKTUALNIJ TABELE
            WYNIKÓW
        </button>
        <span class="float-right">
            <label for="time_frame">Wybierz zakres do zeskrobania</label>
            <select name="time_frame" id="time_frame">
                <option value="Today">Today</option>
                <option value="This Week" selected>This Week</option>
            </select>
        </span>
        <br><br>

        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>l.p.</th>
                <th>Nazwa</th>
                <th>Strava ID</th>
                <th>Typ</th>
                <th>Kategoria</th>
                <th>Strefa</th>
                <th>Sektor</th>
                {#                    <th>Ostatnia aktualizacja</th>#}
                <th>
                    <label for="checkAll">
                        <input type="checkbox" id="checkAll" class="check"> Dodaj do aktualizacji
                    </label>
                </th>

            </tr>
            </thead>
            <tbody>
            {% for segment in segments|dictsort:'strava_segment_name' %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ segment.strava_segment_name }}</td>
                    <td>
                        <a href="https://www.strava.com/segments/{{ segment.strava_segment_id }}" target="_blank">{{ segment.strava_segment_id }}</a>
                    </td>
                    <td>{{ segment.get_srodunia_segment_type_display }}</td>
                    <td>{{ segment.get_srodunia_segment_cat_display }}</td>
                    <td>{{ segment.get_srodunia_segment_zone_display }}</td>
                    <td>{{ segment.get_srodunia_segment_section_display }}</td>
                    {#                            <td>None</td> <!-- TODO: Zrobić to kiedyś -->#}
                    <td><label>
                        <input type="checkbox" class="check" name="strava_segment_id"
                               value="{{ segment.strava_segment_id }}">
                    </label></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </form>
{% endblock %}
{% block scripts %}
    <script>

        $("#checkAll").click(function () {
            $(".check").prop('checked', $(this).prop('checked'));
        });
    </script>
{% endblock %}

scraper/templates/scraper/scrape_members.html
{% extends 'base.html' %}
{% block title %}
    Scrape Club Members
{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <button class="btn btn-outline-danger" type="submit">UAKTUALNIJ LISTĘ ZAWODNIKÓW</button><br><br>
    </form>
    <h3>Zawodnicy klubu EWODD RACE TEAM</h3>
    <table class="table table-striped table-hover table-bordered">
        <thead>
        <tr>
            <th>l.p.</th>
            <th>Zawodnik</th>
            <th>Strava ID</th>
        </tr>
        </thead>
        <tbody>
        {% for athlete in athletes|dictsort:'strava_athlete_name' %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><img class="rounded-circle" style="height: 35px; width: 35px "
                         src="{{ athlete.athlete_avatar_img_url }}" alt="">{{ athlete.strava_athlete_name }}</td>
                <td>{{ athlete.strava_athlete_id }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

scraper/templates/scraper/scrape_segments.html
{% extends 'base.html' %}
{% block title %}
    Scrape Starred Segments
{% endblock %}
{% block content %}
    <form action="" method="post">{% csrf_token %}
        <button class="btn btn-outline-danger" type="submit">UAKTUALNIJ LISTĘ SEGMENTÓW</button><br><br>
    </form>
        <table class="table table-striped table-hover table-bordered">
            <thead>
            <tr>
                <th>l.p.</th>
                <th>Nazwa</th>
                <th>STRAVA ID</th>
                <th>Typ</th>
                <th>Kategoria</th>
                <th>Strefa</th>
                <th>Sekcja</th>
                <th>Data Dodania</th>
            </tr>
            </thead>
            <tbody>
            {% for segment in segments|dictsort:'strava_segment_name' %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ segment.strava_segment_name }}</td>
                    <td>
                        <a href="https://www.strava.com/segments/{{ segment.strava_segment_id }}">{{ segment.strava_segment_id }}</a>
                    </td>
                    <td>{{ segment.get_srodunia_segment_type_display }}</td>
                    <td>{{ segment.get_srodunia_segment_cat_display }}</td>
                    <td>{{ segment.get_srodunia_segment_zone_display }}</td>
                    <td>{{ segment.get_srodunia_segment_section_display }}</td>
                    <td>{{ segment.date_added }}</td>
                </tr>
            {% endfor %}

            </tbody>
        </table>
    </form>
{% endblock %}

scraper/templates/scraper/scraper_home.html
{% extends 'base.html' %}
{% block title %}
    Scraper_Home
{% endblock %}
{% block content %}
    <div class="container">
        <ol>
            <li><a href="{% url 'scrape_members' %}">Pobierz zawodników</a></li>
            <li><a href="{% url 'scrape_segments' %}">Pobierz segmenty</a></li>
            <li><a href="{% url 'scrape_leaderboards' %}">Pobierz tabele wyników</a></li>
        </ol>
    </div>
{% endblock %}